// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhLTMRY6MFo6Tdxi1J3wiuJo3u1ePcEbI',
    appId: '1:213597272138:web:f2fedd6d79612bd3f80eb3',
    messagingSenderId: '213597272138',
    projectId: 'tractorapp-50795',
    authDomain: 'tractorapp-50795.firebaseapp.com',
    storageBucket: 'tractorapp-50795.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3oPYQhRfL_DcfYmz87wXTuhBYVwffaw8',
    appId: '1:213597272138:android:c725371fd1c62094f80eb3',
    messagingSenderId: '213597272138',
    projectId: 'tractorapp-50795',
    storageBucket: 'tractorapp-50795.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLMB-_hwt7648Q1l_54R6bn0TF1RtlKvE',
    appId: '1:213597272138:ios:3849f84067c3ba64f80eb3',
    messagingSenderId: '213597272138',
    projectId: 'tractorapp-50795',
    storageBucket: 'tractorapp-50795.appspot.com',
    iosClientId: '213597272138-67ffc85u2n4i27g7rlldfp87umk5tqt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tractorapp',
  );
}
